[2022-01-06 19:26:03,763] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: hello_world.send_mail scheduled__2022-01-06T13:55:00+00:00 [queued]>
[2022-01-06 19:26:03,771] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: hello_world.send_mail scheduled__2022-01-06T13:55:00+00:00 [queued]>
[2022-01-06 19:26:03,771] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-06 19:26:03,771] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-01-06 19:26:03,771] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-06 19:26:03,781] {taskinstance.py:1259} INFO - Executing <Task(EmailOperator): send_mail> on 2022-01-06 13:55:00+00:00
[2022-01-06 19:26:03,783] {standard_task_runner.py:52} INFO - Started process 74886 to run task
[2022-01-06 19:26:03,790] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'hello_world', 'send_mail', 'scheduled__2022-01-06T13:55:00+00:00', '--job-id', '118', '--raw', '--subdir', 'DAGS_FOLDER/email_test_demo.py', '--cfg-path', '/var/folders/3z/fyvld5jd6lxbb7nt49h4jx1h0000gn/T/tmp1u_hswny', '--error-file', '/var/folders/3z/fyvld5jd6lxbb7nt49h4jx1h0000gn/T/tmp0l4wyv2r']
[2022-01-06 19:26:03,792] {standard_task_runner.py:77} INFO - Job 118: Subtask send_mail
[2022-01-06 19:26:03,844] {logging_mixin.py:109} INFO - Running <TaskInstance: hello_world.send_mail scheduled__2022-01-06T13:55:00+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2022-01-06 19:26:03,888] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=some_email@gmail.com
AIRFLOW_CTX_DAG_OWNER=nivedita
AIRFLOW_CTX_DAG_ID=hello_world
AIRFLOW_CTX_TASK_ID=send_mail
AIRFLOW_CTX_EXECUTION_DATE=2022-01-06T13:55:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-06T13:55:00+00:00
[2022-01-06 19:26:03,898] {logging_mixin.py:109} WARNING - /Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/email.py:102 PendingDeprecationWarning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2022-01-06 19:26:03,898] {configuration.py:381} WARNING - section/key [smtp/smtp_user] not found in config
[2022-01-06 19:26:03,899] {email.py:208} INFO - Email alerting: attempt 1
[2022-01-06 19:26:03,900] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/operators/email.py", line 88, in execute
    conn_id=self.conn_id,
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/email.py", line 66, in send_email
    **kwargs,
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/email.py", line 102, in send_email_smtp
    send_mime_email(e_from=smtp_mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/email.py", line 210, in send_mime_email
    conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/email.py", line 244, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused
[2022-01-06 19:26:03,909] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=hello_world, task_id=send_mail, execution_date=20220106T135500, start_date=20220106T135603, end_date=20220106T135603
[2022-01-06 19:26:03,921] {logging_mixin.py:109} WARNING - /Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-01-06 19:26:03,922] {logging_mixin.py:109} WARNING - /Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
[2022-01-06 19:26:03,923] {logging_mixin.py:109} WARNING - /Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
[2022-01-06 19:26:03,925] {logging_mixin.py:109} WARNING - /Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
[2022-01-06 19:26:03,926] {logging_mixin.py:109} WARNING - /Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
[2022-01-06 19:26:03,927] {logging_mixin.py:109} WARNING - /Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
[2022-01-06 19:26:03,928] {logging_mixin.py:109} WARNING - /Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
[2022-01-06 19:26:03,929] {logging_mixin.py:109} WARNING - /Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
[2022-01-06 19:26:03,930] {logging_mixin.py:109} WARNING - /Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
[2022-01-06 19:26:03,931] {logging_mixin.py:109} WARNING - /Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
[2022-01-06 19:26:03,933] {logging_mixin.py:109} WARNING - /Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
[2022-01-06 19:26:03,935] {logging_mixin.py:109} WARNING - /Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
[2022-01-06 19:26:03,945] {logging_mixin.py:109} WARNING - /Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/email.py:102 PendingDeprecationWarning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2022-01-06 19:26:03,946] {configuration.py:381} WARNING - section/key [smtp/smtp_user] not found in config
[2022-01-06 19:26:03,946] {email.py:208} INFO - Email alerting: attempt 1
[2022-01-06 19:26:03,951] {configuration.py:381} WARNING - section/key [smtp/smtp_user] not found in config
[2022-01-06 19:26:03,951] {email.py:208} INFO - Email alerting: attempt 1
[2022-01-06 19:26:03,953] {taskinstance.py:1751} ERROR - Failed to send email to: ['some_email@gmail.com']
Traceback (most recent call last):
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/operators/email.py", line 88, in execute
    conn_id=self.conn_id,
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/email.py", line 66, in send_email
    **kwargs,
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/email.py", line 102, in send_email_smtp
    send_mime_email(e_from=smtp_mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/email.py", line 210, in send_mime_email
    conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/email.py", line 244, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2093, in email_alert
    send_email(self.task.email, subject, html_content)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/email.py", line 66, in send_email
    **kwargs,
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/email.py", line 102, in send_email_smtp
    send_mime_email(e_from=smtp_mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/email.py", line 210, in send_mime_email
    conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/email.py", line 244, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1749, in handle_failure
    self.email_alert(error)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2095, in email_alert
    send_email(self.task.email, subject, html_content_err)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/email.py", line 66, in send_email
    **kwargs,
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/email.py", line 102, in send_email_smtp
    send_mime_email(e_from=smtp_mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/email.py", line 210, in send_mime_email
    conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/email.py", line 244, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused
[2022-01-06 19:26:03,963] {standard_task_runner.py:92} ERROR - Failed to execute job 118 for task send_mail
Traceback (most recent call last):
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/operators/email.py", line 88, in execute
    conn_id=self.conn_id,
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/email.py", line 66, in send_email
    **kwargs,
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/email.py", line 102, in send_email_smtp
    send_mime_email(e_from=smtp_mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/email.py", line 210, in send_mime_email
    conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/email.py", line 244, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused
[2022-01-06 19:26:04,011] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-01-06 19:26:04,040] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
