[2022-01-07 15:36:37,798] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: booking_ingestion.transform_data manual__2022-01-07T10:06:24.593904+00:00 [queued]>
[2022-01-07 15:36:37,817] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: booking_ingestion.transform_data manual__2022-01-07T10:06:24.593904+00:00 [queued]>
[2022-01-07 15:36:37,817] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-07 15:36:37,817] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-07 15:36:37,817] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-07 15:36:37,838] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): transform_data> on 2022-01-07 10:06:24.593904+00:00
[2022-01-07 15:36:37,849] {standard_task_runner.py:52} INFO - Started process 89939 to run task
[2022-01-07 15:36:37,866] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'booking_ingestion', 'transform_data', 'manual__2022-01-07T10:06:24.593904+00:00', '--job-id', '331', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/var/folders/3z/fyvld5jd6lxbb7nt49h4jx1h0000gn/T/tmp_raacexc', '--error-file', '/var/folders/3z/fyvld5jd6lxbb7nt49h4jx1h0000gn/T/tmpr7ndbchb']
[2022-01-07 15:36:37,870] {standard_task_runner.py:77} INFO - Job 331: Subtask transform_data
[2022-01-07 15:36:37,967] {logging_mixin.py:109} INFO - Running <TaskInstance: booking_ingestion.transform_data manual__2022-01-07T10:06:24.593904+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2022-01-07 15:36:38,044] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=nivedita
AIRFLOW_CTX_DAG_ID=booking_ingestion
AIRFLOW_CTX_TASK_ID=transform_data
AIRFLOW_CTX_EXECUTION_DATE=2022-01-07T10:06:24.593904+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-01-07T10:06:24.593904+00:00
[2022-01-07 15:36:38,049] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: transform_data() missing 1 required positional argument: 'exec_date'
[2022-01-07 15:36:38,059] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=booking_ingestion, task_id=transform_data, execution_date=20220107T100624, start_date=20220107T100637, end_date=20220107T100638
[2022-01-07 15:36:38,072] {standard_task_runner.py:92} ERROR - Failed to execute job 331 for task transform_data
Traceback (most recent call last):
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: transform_data() missing 1 required positional argument: 'exec_date'
[2022-01-07 15:36:38,118] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-01-07 15:36:38,149] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
